apiVersion: apps/v1
kind: Deployment
metadata:
  name: sda-capstone
  namespace: sda-capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sda-capstone
  template:
    metadata:
      labels:
        app: sda-capstone
    spec:
      containers:
        - name: backend
          image: day27-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: FRONTEND_URL
              value: "http://localhost:5173"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

        - name: frontend
          image: day27-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
