apiVersion: v1
kind: Service
metadata:
  name: sda-capstone-backend
  namespace: sda-capstone
spec:
  selector:
    app: sda-capstone
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: sda-capstone-frontend
  namespace: sda-capstone
spec:
  selector:
    app: sda-capstone
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: NodePort
