apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sda-training-storage-pvc
  namespace: sda-training

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: manual