apiVersion: v1
kind: PersistentVolume
metadata:
  name: sda-training-local-pv
  labels:
    app: sda-training
    component: storage

spec:
  capacity:
    storage: 1Gi

  accessModes:
    - ReadWriteOnce

  persistentVolumeReclaimPolicy: Retain

  storageClassName: manual

  hostPath:
    path: /tmp/sda-training
    type: DirectoryOrCreate