apiVersion: v1
kind: Secret
metadata:
  name: sda-training-secrets
  namespace: sda-training
type: Opaque
stringData:
  JWT_SECRET: "day17-local-jwt-secret"
  MONGODB_URI: "mongodb://admin:password@mongodb-service:27017/sda_training?authSource=admin"
  POSTGRES_URL: "postgresql://postgres:password@postgresql-service:5432/sda_training"
  REDIS_URL: "redis://redis-service:6379"
  MONGO_ROOT_PASSWORD: "password"
  POSTGRES_PASSWORD: "password"